trigger:
- main
variables:
- group: MyGroupVariable
pool:
  vmImage: 'ubuntu-latest'

steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: $(azureSubscription)
    subscriptionId: $(subscriptionId)
    action: 'Create Or Update Resource Group'
    resourceGroupName: $(resourceGroupName)
    location: $(Location)
    templateLocation: 'Linked artifact'
    csmFile: '$(Build.SourcesDirectory)/IaC/ResourceGroup.json'
    deploymentMode: 'Incremental'
